### PR TITLE
Add builtwithnuxt.com to showcase.md

### PR DESCRIPTION
**Pull request by Guillaume-Souillard**

### CODE REVIEW

**Comment by ansidev** [comment]
@Guillaume-Souillard At this time, I think the Submit project link has some issues, so if you want to merge this PR, please remove it. You can create a new MR for that in the future.

**Comment by Guillaume-Souillard** [comment]
> @Guillaume-Souillard At this time, I think the Submit project link has some issues, so if you want to merge this PR, please remove it. You can create a new MR for that in the future.

Hi, I deployed a patch today, normally there is no more problem on the submit page :P

**Comment by ansidev** [comment]
> > @Guillaume-Souillard At this time, I think the Submit project link has some issues, so if you want to merge this PR, please remove it. You can create a new MR for that in the future.
> 
> Hi, I deployed a patch today, normally there is no more problem on the submit page :P

I don't think so.

**Comment by Guillaume-Souillard** [comment]
what kind of problem are you having on this page ?

**Pull request closed without merging**
